<?php

/**
 * @file
 *
 * Hook implementations for my_module module.
 */

/**
 * Implements hook_mail().
 */
function my_module_mail($key, &$message, $params) {
  switch ($key) {
    case 'node_pdf_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      $message['params']['attachments'][] = $params['attachments'];
      break;
  }
}